 SET NAMES utf8mb4 ;
-- 默认组织机构
INSERT INTO asset_department ( `id`, `name`, `responsible_user`, `telephone`, `parent_id`, `memo`, `gmt_create`, `gmt_modified`, `create_user`, `modify_user`, `status` ) VALUES ( '1', '部门', NULL, NULL, '0', '0', unix_timestamp( ) * 1000, NULL, '0', '0', '1' );


-- -------------------------------
-- default common operation system
-- -------------------------------
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'os_x_server'  ORDER BY business_id limit 1) where `product_name` = 'os_x_server';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'mac_os_x' ORDER BY business_id limit 1) where `product_name` = 'mac_os_x';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'hp-ux'  ORDER BY business_id limit 1) where `product_name` = 'hp-ux';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'aix' ORDER BY business_id limit 1) where `product_name` = 'aix';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'enterprise_linux' ORDER BY business_id limit 1) where `product_name` = 'enterprise_linux';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'linux_2' ORDER BY business_id limit 1) where `product_name` = 'linux_2';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'windows-nt' ORDER BY business_id limit 1) where `product_name` = 'windows-nt';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'windows_7' ORDER BY business_id limit 1) where `product_name` = 'windows_7';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'windows_8' ORDER BY business_id limit 1) where `product_name` = 'windows_8';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'windows_8.1' ORDER BY business_id limit 1) where `product_name` = 'windows_8.1';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'windows_10' ORDER BY business_id limit 1) where `product_name` = 'windows_10';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'windows_server_2008' ORDER BY business_id limit 1) where `product_name` = 'windows_server_2008';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'windows_server_2012' ORDER BY business_id limit 1) where `product_name` = 'windows_server_2012';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'windows_server_2016' ORDER BY business_id limit 1) where `product_name` = 'windows_server_2016';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'windows_server_2003' ORDER BY business_id limit 1) where `product_name` = 'windows_server_2003';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'linux_enterprise_server' ORDER BY business_id limit 1) where `product_name` = 'linux_enterprise_server';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'suse_linux_enterprise_server' ORDER BY business_id limit 1) where `product_name` = 'suse_linux_enterprise_server';
--
-- update asset_cpe_filter set business_id = (SELECT business_id FROM `asset_hard_soft_lib` WHERE `product_name` = 'ubuntu_linux' ORDER BY business_id limit 1) where `product_name` = 'ubuntu_linux';
